version: '3'

services:

  ### PHP-FPM Container #######################################

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis
    restart: always

  ### PHP Container #######################################

  php:
    build:
      context: ./php
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - 9000
    depends_on:
      - mysql
      - redis
    tty: true
    restart: always

  ### CRONTAB Container #######################################

  crontab:
    build:
      context: ./crontab
    volumes:
      - ${WEB_ROOT}:/var/www/html
    depends_on:
      - mysql
      - redis
    tty: true
    restart: always

  ### Nginx Server Container ##################################

  nginx:
    build:
      context: ./nginx
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/nginx/logs/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    restart: always

  ### MySQL Container #########################################

  mysql:
    build:
      context: ./mysql
    volumes:
      - ../data/mysql:/var/lib/mysql
      #- mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tms-api
    restart: always



  ### Redis Container #########################################

  redis:
    image: redis:3.2.11
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../data/redis:/data
    restart: always

  ### PHPMyAdmin Container #########################################

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: always
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_ARBITRARY=1

  # supervisor
  supervisor:
    build:
      context: ./
      dockerfile: supervisor/Dockerfile
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ../data/supervisor/logs:/var/log/supervisor/
    expose:
      - 9000
      - 9001
    ports:
      - "${HORIZON_PORT}:9001"
    depends_on:
      - php
      - mysql
      - redis
    restart: always

### Volumes Setup ###########################################


volumes:
  mysql_data:
networks:
  default:
    external:
      name: ${USER_NETWORK}